### ISSUE TITLE
Implementing Benchmarks without fidelity spaces

### ISSUE THREAD

**Issue by NeoChaos12** [automl/HPOBench#34]
The protocol for sub-classing AbstractBenchmark in cases where the new benchmark does not support fidelity spaces is unclear. With the current state of the code, not overwriting `AbstractBenchmark.get_fidelity_spaces()` causes a `NotImplementedError` to be thrown every time that method were to be called from such a sub-class's object. This, on its own, is also a valid solution, if the users are aware that they need to catch the error in this particular case and interpret that to mean that multi-fidelity optimization is not supported for this benchmark. However, this should then be a part of the Readme on fidelity spaces.

Another possible solution is to modify `AbstractBenchmark.get_fidelity_spaces()` to return either `None` or an empty `ConfigurationSpace` object by default, thus eliminating the need to overwrite it. Users would still need to be aware of this, and the documentation should reflect this.

**Comment by NeoChaos12** [comment]
I will list out the three possible alternatives that came up in a discussion with @KEggensperger and @PhMueller here along with the pros and cons in my opinion.

1. Allow `NotImplementedError` to be raised and caught.

Pros:
- It's the current state of the code and would only require a note in the documentation as well as a `try...catch` block in the `check_fidelity` wrapper.
- Still pythonic.

Cons
- Not very elegant or user-friendly.
- From a developer perspective, it blurs the distinction between forgetting to implement a method vs intentionally leaving it out.

2. Make `get_fidelity_space()` return an empty `ConfigSpace.ConfgurationSpace` object by default, thus making it optional to overwrite.

Pros: I'm not in favor of this approach and cannot think of any.
Cons:
- Requires a little more effort than **1**.
- Checking if the object is empty isn't the neatest piece of code. One would need to get the list of parameters and check its length. 

3. Same as **2**, but return `None` by default. This is my preferred alternative.

Pros:
- Very clean and user-friendly code.
- Maintains the distinction between a developer side error and intentional feature.

Cons:
- Requires a little more effort than **1** (same as **2**).

**Comment by PhMueller** [comment]
Hey, thanks for the sum up!

But I want to add to your list, why I think option 2 is still the best.

Firstly, returning None is a dangerous thing, since it's pythons default return Value. To find the cause for a None value (especially on container side) is pretty hard because we don't know where it came from. Was it either a user error or a problem with the container interface? An empty configspace would at least indicate that the sending works and the error must be caused by something else. [Ref 1](https://stackoverflow.com/a/14583818), [Ref 2](https://www.reddit.com/r/Python/comments/30yb5t/return_none_or_not_to_return_none/cpx693c/) 

Secondly, and this relates to the first point, using an empty configspace would work and make sense logically, because it means that it was our intention that there are no fidelities in this benchmark (explicit > implicit). It also works as a No-Op and we don't need to check after every function call if it is None! All basic operations (such as get_configuration(), len(), etc) work without an explicit check. 

Visiting the code later, we also know, that we just haven't forgotten to implement it.

Thirdly,  there is at the moment no benchmark without fidelities. Therefore, this is not a standard case. And IMO should be therefore treated outside of the HPOlib. 

And finally, the HPOlib actually can work with empty fidelity spaces. Copy&Pasting the code for an empty fidelity space a single time when writing the benchmark seems pretty easy to me. Changing to a different solution would require changing some points in the interface and cost time. Therefore, I don't really see why we should switch from a working solution. 

I am happy to discuss this again but would postpone it for now while there are still higher priority tasks.

**Comment by NeoChaos12** [comment]
I see your point. Of course, as you said, this is quite low on the priority list. The only utility to discussing it now would be to establish a protocol such that there are no backwards compatibility breaking changes in the future, but I suppose that's also not a big concern at the moment. Let's leave this here for the moment and return to it later, then (if needed).
