### ISSUE TITLE
Check configuration wrapper returns incorrect value

### ISSUE THREAD

**Issue by NeoChaos12** [automl/HPOBench#45]
Here:
https://github.com/automl/HPOlib2/blob/5b20fdc0ebdf133692e84aa442688839e8e69bc3/hpolib/abstract_benchmark.py#L127-L128

The checked and verified value resides in the variable 'config' which should be returned instead of 'configuration' which simply contains the original unverified input to the wrapper.

**Comment by PhMueller** [comment]
Hm, actually I was aware of this thing and I thought it might be better to just return the input value. In my understanding, the given configuration is just checked here. In a second step, the config_as_dict_wrapper then handles it. 

I thought it might be useful to have separate functions for checking and handling. 
This allows us to have more functionality and flexibility in the benchmarks. 
For example, if users want to have a benchmark, which supports lists as configurations, they couldn't since the "wrappers" always return a dictionary. 
But having a check function, the configuration could be checked regardless of being a dict, CS.Configuration, List, or Array. 
Then, the users could select the corresponding wrapper function to get the configuration in the right format. This wrapper casts the input configuration (all possible types (Dict, List, Config,...)) to the correct type (for example np.array).  

I think this gives us more flexibility for the future. And since it is not something the user has to understand in detail, we can have different functions instead of a single one.

**Comment by NeoChaos12** [comment]
This actually ties in with #49 and a discussion I recently had with @KEggensperger . The type-hints provided in the original ABC `AbstractBenchmark` for `objective_function()`'s inputs are a design decision that needs some consideration. Should that definition only accept a dict or should it accept the full spectrum of input types as well? I had the same view point as you in that the person implementing a new benchmark should be allowed to decide how to write their code, and should only be aware that the user could potentially provide any of these 4 input types. The wrappers themselves are not compulsory to use - they are an accessory that a developer can choose to use if they feel the need to, and are then aware of what the wrappers do. @KEggensperger made a valid counter-argument that perhaps getting wrapped up in the idea of providing so much flexibility is not necessarily a good idea from the perspective of efficiency. 

That said, I still disagree with not casting the configuration to a specific type, although I would actually go a step further and suggest that they always be cast into `ConfigSpace.ConfigurationSpace` objects instead of dictionaries. As it stands, if the wrapper only checks the configuration for correctness and doesn't cast it into a pre-determined type, the objective functions must then implement code for handling all 4 data types, which I find rather redundant. A "best of both worlds" solution is to include an optional argument to the wrapper itself, specifying which of the four types it would prefer the input to be cast into. This way, existing code will not need to be changed as `dict` can be the default type.
