### ISSUE TITLE
Configuration as list: missing feature or bug?

### ISSUE THREAD

**Issue by NeoChaos12** [automl/HPOBench#46]
I read in #10 that passing configurations as lists should be valid, and I see that a corresponding wrapper is present in AbstrackBenchmark [here](https://github.com/automl/HPOlib2/blob/5b20fdc0ebdf133692e84aa442688839e8e69bc3/hpolib/abstract_benchmark.py#L186-L205), but it is never used. I'm not sure if this is intentional, i.e. configurations can no longer be input as lists, or a bug.

EDIT: I re-read the code of that wrapper, and it doesn't quite seem to handle the case of lists either. So the question remains if regular Python lists are to be supported by HPOlib as mentioned in #10.

**Comment by PhMueller** [comment]
We had benchmarks with the configurations given as a list, but you are right: Currently, we don't have any. I haven't removed the list support yet, because I thought it would be nice to allow users, who are familiar with the hpolib1.5 (old hpolib2) to still use the lists as configurations for their own benchmarks. 

Ah.  It looks like that during the last restructurings, the code for handling Lists and Arrays was deleted in the wrapper. That's a good point. Thanks!

**Comment by NeoChaos12** [comment]
That was my first guess as well. I think we could also remove the old `_configuration_as_array` and `_configuration_as_dict` wrappers since they are pretty much just artifacts at this point. If we need to retain the ability to cast inputs to specific types, I would recommend the solution I posted in #45.
